spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: ${{ secrets.DATASOURCE_URL }}
    driverClassName: org.h2.Driver
    username: ${{ secrets.DATASOURCE_USERNAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
  jpa.hibernate.ddl-auto: update
