spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: @datasource.url@
    driverClassName: org.h2.Driver
    username: @datasource.user@
    password: @datasource.password@
  jpa.hibernate.ddl-auto: update
