spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: ${datasourceUrl}
    driverClassName: org.h2.Driver
    username: ${datasourceUser}
    password: ${datasourcePassword}
  jpa.hibernate.ddl-auto: update
