spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:file:./db/dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.hibernate.ddl-auto: update
