spring:
  config.import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
  jmx:
    enabled: false
  springdoc:
    swagger-ui:
      enabled: true
      url: /docs/openapi.json
      path: /swagger-ui.html
    api-docs:
      enabled: true
      path: /v3/api-docs
alphavantage:
  api.key: ${ALPHAVANTAGE_API_KEY}