name: CI with maven build and publish docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B -Ddatasource.user=${{ secrets.DATASOURCE_USERNAME }} -Ddatasource.password=${{ secrets.DATASOURCE_PASSWORD }} package

    - name: Build and publish docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: piotrholda/private
        tags: portfolio-manager
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
