name: CI with maven build and publish docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v2

#    - name: Copy secrets to environment variables
#      uses: Firenza/secrets-to-env@v1.1.0
#      with:
#        secrets: ${{ toJSON(secrets) }}
#        secret_filter_regex: DATASOURCE_*

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DdatasourceUrl=${{ secrets.DATASOURCE_URL }}  -DdatasourceUser=${{ secrets.DATASOURCE_USER }} -DdatasourcePassword=${{ secrets.DATASOURCE_PASSWORD }}

    - name: Build and publish docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: piotrholda/private
        tags: portfolio-manager
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
